---
server:
  port: 8888
spring:
  security:
    user:
      name: navneet
      password: navneet
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/NavneetPrakashSingh/spring-cloud-config-chocolate-bar
          #username:uname
          #password:pass
          search-paths:
            - 'company*'